- Do not delete logs if empty.- Ensure logs are not empty by always outputting something- Improve consistency/readability of ocsp logging

diff --git a/Pod/Support/OSX/RunTestsTargetWithSlimPort b/Pod/Support/OSX/RunTestsTargetWithSlimPort
--- a/Pod/Support/OSX/RunTestsTargetWithSlimPort
+++ b/Pod/Support/OSX/RunTestsTargetWithSlimPort
@@ -8,34 +8,35 @@ APP_PATH=${TARGET_BUILD_DIR}/${PRODUCT_NAME}.app
 # Main Subroutines
 
 main() {
-	log "== RunSlimTestTargetWithSlimPort~macOSX:$SLIM_PORT =="
+	log "RunSlimTestTargetWithSlimPort~macOSX"
+	log "Fitnesse Slim Port: $SLIM_PORT"
+	log "Xcode Build Product $APP_PATH"
 	run_test_system
 	exit $?
 }
 
 run_test_system() {
-	log "Test System Executable = $EXECUTABLE_PATH"
+	
 	local LOGFILE=$(get_log_file_path)
 	launch_osx_app $LOGFILE
 	write_logs_to_console $LOGFILE
-	log "*** App Exited ***"
 	return $?
 }
 
 launch_osx_app() {
-	log "*** Launching ${PRODUCT_NAME}.app ***"
+	log "Launching '${PRODUCT_NAME}.app'"
 	local LOGFILE=$1
-	$EXECUTABLE_PATH $SLIM_PORT > $LOGFILE 2>&1
+	log "macOS System log started" > $LOGFILE 
+	$EXECUTABLE_PATH $SLIM_PORT >> $LOGFILE 2>&1
+	log "macOS System log ended" >> $LOGFILE
 }
 
 ## Logging Subroutines
 
 write_logs_to_console() {
 	local LOGFILE=$1
-	tidy_zero_line_app_log_file $LOGFILE
-	if [ $? -eq 1 ]; then
-		cat $LOGFILE 
-	fi
+	log "Reading log file: $LOGFILE"
+	cat $LOGFILE 
 }
 
 get_log_file_path() {
@@ -60,11 +61,11 @@ tidy_zero_line_app_log_file(){
 # Logging Subroutined
 
 log() {
-	echo "[OCSP_RUN]: INFO $1"
+	echo "[OCSP_RUN] INFO: $1"
 }
 
 error() {
-	>&2 echo "[OCSP_RUN]: ERROR $1"
+	>&2 echo "[OCSP_RUN] ERROR: $1"
 	exit 1
 }
 
diff --git a/Pod/Support/iOS/RunTestsTargetWithSlimPort b/Pod/Support/iOS/RunTestsTargetWithSlimPort
--- a/Pod/Support/iOS/RunTestsTargetWithSlimPort
+++ b/Pod/Support/iOS/RunTestsTargetWithSlimPort
@@ -27,15 +27,17 @@ get_app_devicetypeid() {
 slim_system_wait() {
 	
 	local EXECUTABLE_PID=$(<.simctl.pid)
-	
-	log "Waiting for Slim System... ($EXECUTABLE_PID) $(date)"
-	
-	while ps -p $EXECUTABLE_PID
+	local INTERVAL=1
+	local COUNT=0
+
+	log_hrule
+	log "Waiting for System Under Test... (ProcessID: $EXECUTABLE_PID)";
+	while ps -p $EXECUTABLE_PID > /dev/null
 	do
-		sleep 1
+		sleep $INTERVAL;
+		((COUNT++))
 	done
-	
-	log "Slim System Exited $(date)"
+	log "System Under Test exited (running for $COUNT second(s))"
 }
 
 run_test_system() {
@@ -52,17 +54,16 @@ run_test_system() {
 }
 
 start_slim() {
-	log "Start Slim Test Sytem"
+	log "Starting System Under Test"
+	log_hrule
 	$MYPATH/simctl $APPLICATION_PATH $SLIM_PORT
 }
 
 print_test_system_log() {
-	local LOGFILE=$($MYPATH/simctl log $1)
-	if [ -z $LOGFILE ]; then
-		log "*WARNING* No test system log messages were found (use os_log() or NSLog())"
-	else
-		print_logfile_contents $LOGFILE
-	fi
+	local STARTTIME=$1
+	local LOGFILE=$($MYPATH/simctl log $STARTTIME)
+	log "Reading log file: $LOGFILE"
+	cat $LOGFILE
 }
 
 log_simctl_error() {
@@ -70,26 +71,25 @@ log_simctl_error() {
 	error "**ABORTING** Exit Code error detected when executing Slim Test Sytem with ($MYPATH/simctl)"
 }
 
-print_logfile_contents() {
-	log "********* $1 *********"
-	cat $1
-	log "********* End of Log ***********"
-}
-
 main() {
-	log "== RunSlimTestTargetWithSlimPort~iOS:$SLIM_PORT $(date)=="
-	log "Test System Suggested SDK: $DEPLOYMENT_TARGET_VALUE"
-	log "Test System Path: $APPLICATION_PATH"
+	log "RunSlimTestTargetWithSlimPort~iOS"
+	log "Fitnesse Slim Port: $SLIM_PORT"
+	log "Xcode Suggested SDK: $DEPLOYMENT_TARGET_VALUE"
+	log "Xcode Build Product: $APPLICATION_PATH"
 	run_test_system 
 	exit $?
 }
 
 log() {
-	echo "[OCSP_RUN]: INFO $1"
+	echo "[OCSP_RUN] INFO: $1"
+}
+
+log_hrule() {
+	log "------------------------------------------------"
 }
 
 error() {
-	>&2 echo "[OCSP_RUN]: ERROR $1"
+	>&2 echo "[OCSP_RUN] ERROR: $1"
 	exit 1
 }
 
diff --git a/Pod/Support/iOS/simctl b/Pod/Support/iOS/simctl
--- a/Pod/Support/iOS/simctl
+++ b/Pod/Support/iOS/simctl
@@ -41,11 +41,12 @@ get_device_id() {
 }
 
 log() {
-	echo "[OCSP_SIMCTL] INFO: $1"
+	local LINE="[OCSP_SIM] INFO: $1"
+	echo $LINE
 }
 
 error() {
-	>&2 echo "[OCSP_SIMCTL] ERROR: $1"
+	>&2 echo "[OCSP_SIM] ERROR: $1"
 }
 
 preflight() {
@@ -56,12 +57,12 @@ preflight() {
 }
 
 install() {
-	log "Installing App Identifier:$APP_IDENTIFIER"
+	log "Installing App Bundle '$APP_IDENTIFIER'"
 	xcrun simctl install booted $APPLICATION_PATH
 }
 
 launch() {
-	log "Launching... (App Identifer:$APP_IDENTIFIER, Slim Port: $SLIMSERVER_PORT)"
+	log "Launching... (Slim Port: $SLIMSERVER_PORT)"
 	rm $PID_FILE 2> /dev/null
 	echo $(xcrun simctl launch booted $APP_IDENTIFIER $SLIMSERVER_PORT) | cut -d " " -f2 > $PID_FILE
 }
@@ -73,28 +74,22 @@ pid() {
 write_logs() {
 
 	# DO NOT ECHO FROM HERE. OUTPUT IS RESERVERD FOR RETURNING THE FILENAME
-	
 	PID_ID=$(cat $PID_FILE)
 	local LOGDIR="Logs"
 	local LOGPATH="$(pwd)/$LOGDIR"
 	local LOGFILENAME="$(date +%Y%m%d-%H%M%S).log"
 	local LOGFILE="$LOGPATH/$LOGFILENAME"
-
 	mkdir -p $LOGPATH
-	xcrun simctl spawn booted log show --start $LOG_START_DATE --style compact --info --predicate "processID == $PID_ID" > $LOGFILE 2>&1
 
-	# Check number of lines in logfile before returning a log file
-	if [ $(grep -c '' $LOGFILE) -eq 1 ]; then
-		rm $LOGFILE
-	else
-		echo $LOGFILE
-	fi
-	
+	log "Show Simulator log process: $PID_ID, date: $LOG_START_DATE" >> $LOGFILE
+	xcrun simctl spawn booted log show --start $LOG_START_DATE --style compact --info --predicate "processID == $PID_ID" >> $LOGFILE 2>&1
+	log "Simulator log ended" >> $LOGFILE
+	echo $LOGFILE
 }
 
 main() {
 
-	log "== Launching Slim Host App $(xcrun simctl --version)  =="
+	log "Launching Slim Host App $(xcrun simctl --version)"
 	APP_IDENTIFIER=$(defaults read $APPLICATION_PATH/Info CFBundleIdentifier)
 
 	preflight
