Add Java System Check and Option to Download to LaunchFitnesse Script

diff --git a/Pod/Support/SharedSupport/LaunchFitnesse b/Pod/Support/SharedSupport/LaunchFitnesse
--- a/Pod/Support/SharedSupport/LaunchFitnesse
+++ b/Pod/Support/SharedSupport/LaunchFitnesse
@@ -38,6 +38,20 @@ done
 # Subroutines #
 ###############
 
+function java_check {
+	if ! type java &> /dev/null ;  then
+		echo "Java (JRE) not found"
+    	echo "Download the latest version of Java?"
+		select yn in "Get Java for Mac" "Not Now"; do
+			case $yn in 
+				"Get Java for Mac" ) open "http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html"; break;;
+				"Not Now" ) break;;
+			esac
+		done
+		exit 0
+	fi
+}
+
 function fitnesse_kill {
 	lsof -n -i4TCP:$FITNESSE_PORT | awk ' { print $2 }' | sed -n 2p | xargs kill -9
 }
@@ -100,6 +114,8 @@ function fitnesse_launch {
 
 function fitnesse_main {
 
+	# Check Java Exists	
+	java_check
 	# Check Fitnesse Exists
 	fitnesse_check	
 	# Enable Job Control
@@ -108,6 +124,7 @@ function fitnesse_main {
 	fitnesse_launch
 	# Return Foreground control to Fitnesse
 	fg %1
+	
 }
 
 
