DEV: Test command returns Fitnesse to it's either shutdown or running state after completing

diff --git a/Pod/Support/SharedSupport/LaunchFitnesse b/Pod/Support/SharedSupport/LaunchFitnesse
--- a/Pod/Support/SharedSupport/LaunchFitnesse
+++ b/Pod/Support/SharedSupport/LaunchFitnesse
@@ -15,7 +15,7 @@ FITNESSE_PORT=8080
 FITNESSE_EXECUTABLE_PATH=${BUNDLE_DIR}/fitnesse-standalone.jar
 FITNESSE_ROOT_CONTENT_FILE=FitnesseRoot/content.txt
 FITNESSE_URL=http:"//localhost:${FITNESSE_PORT}/"
-FITNESSE_TEST_OUTPUT=${PROJECT_DIR}/Fitnesse-Test-Report.xml
+FITNESSE_TEST_OUTPUT=/tmp/Fitnesse-Test-Report.xml
 FITNESSE_ROOT=.
 FITNESSE_TEST_SUITE=
 
@@ -171,22 +171,35 @@ function fitnesse_main {
 	# Enable Job Control
 	set -o monitor
 	
-	# LAUNCH Fitnesse in the background, wait for it to respond, then open in a browser.
+	# LAUNCH Fitnesse in the background, wait for it to begin responsding
 	fitnesse_run
+	
+	local RETURN_RESULT=$?
 	
 	popd 2>&1 > /dev/null
 	
+	return $RETURN_RESULT
+	
 }
 
+FITNESSE_MAIN_EXECUTED=0
+FITNESSE_MAIN_ALREADY_RUNNING=1
+
 function fitnesse_run {
+	
+	local MAIN_RESULT=-1
+	
 	if ! fitnesse_running; then 
 		fitnesse_start
 		fitnesse_wait
 		fitnesse_setup
+		MAIN_RESULT=0
 	else 
+		MAIN_RESULT=1
 		echo "[OCSP_CTL] Fitnesse Already Running - $FITNESSE_URL"
 	fi
 	
+	return $MAIN_RESULT
 }
 
 function fitnesse_launch_in_browser {
@@ -195,18 +208,36 @@ function fitnesse_launch_in_browser {
 }
 
 function fitnesse_generate_test_suite_report {
+	
 	fitnesse_main
+	
+	local MAIN_RESULT_CODE=$?
+	
 	fitnesse_write_suite_results
+	
+	if [ $MAIN_RESULT_CODE -eq $FITNESSE_MAIN_EXECUTED ]; then
+		fitnesse_shutdown
+	fi
 }
 
 function fitnesse_write_suite_results {
-	echo "[OCSP_CTL] Run Test Action"
+	
+	echo "[OCSP_CTL] Run Test"
 	echo "[OCSP_CTL] Test Suite=$FITNESSE_TEST_SUITE"
 	echo "[OCSP_CTL] Test Output=$FITNESSE_TEST_OUTPUT"
-	echo "[OCSP_CTL] FITNESSE: Run Tests..."
+	
 	cmd=$FITNESSE_URL$FITNESSE_TEST_SUITE\?suite\&format\=junit 
+	echo "[OCSP_CTL] FITNESSE: $cmd"
+	
 	curl $cmd -s > $FITNESSE_TEST_OUTPUT
-	echo "[OCSP_CTL] Testing Report Generated (curl exit code=$?)"
+	CURL_RESULT=$?
+	
+	if [ $CURL_RESULT -eq 1 ]; then
+		echo "[OCSP_CTL] ERROR: Could Not Download Test Report (curl exit code=$CURL_RESULT)"
+	else
+		echo "[OCSP_CTL] Test Succeeded (curl exit code=$CURL_RESULT)"
+	fi
+	
 }
 
 ########
@@ -228,7 +259,6 @@ function main {
 		
 	TEST)  
 		fitnesse_generate_test_suite_report
-		fitnesse_shutdown
 		;;
 		
 	esac
