Reverting changes to scripts to remove logging.

diff --git a/Pod/Support/iOS/RunTestsTargetWithSlimPort b/Pod/Support/iOS/RunTestsTargetWithSlimPort
--- a/Pod/Support/iOS/RunTestsTargetWithSlimPort
+++ b/Pod/Support/iOS/RunTestsTargetWithSlimPort
@@ -30,31 +30,26 @@ slim_system_wait() {
 	
 	local EXECUTABLE_PID=
 	local EXECUTABLE_NAME=$(get_app_executable_name)
-
-	echo >&2 "[OCSP_RUN] Waiting for Slim Test System To Launch"
-	echo >&2 "[OCSP_RUN] Info: $(date)"
+	
+	echo "[OCSP_RUN] Waiting for Slim Test System To Launch"
 	while [ -z "$EXECUTABLE_PID" ] 
 	do
-		echo >&2 "[OCSP_RUN] Info: Waiting for $EXECUTABLE_NAME"
-		sleep 1
 		EXECUTABLE_PID=$(pgrep "$EXECUTABLE_NAME")
 	done
 	
-	echo >&2 "[OCSP_RUN] Slim System Detected ($EXECUTABLE_PID)"
+	echo "[OCSP_RUN] Slim System Detected ($EXECUTABLE_PID)"
 	while [[ "$EXECUTABLE_PID" ]]
 	do
 		EXECUTABLE_PID=$(pgrep "$EXECUTABLE_NAME")
 		sleep 0.5
 	done
-
 }
 
 ios_sim_launch() {
 	
-	echo >&2 "[OCSP_RUN] == Start Slim Test Sytem (ios-sim version $(ios-sim --version), Node Version: $(node -v)) =="
-	ios-sim start --devicetypeid "$2"
-	echo >&2 "[OCSP_RUN] == Started UP =="
-	ios-sim launch "$1" --devicetypeid "$2" --args "$3" --verbose 1>&2 &
+	echo "[OCSP_RUN] == Start Slim Test Sytem (ios-sim version $(ios-sim --version), Node Version: $(node -v)) =="
+
+	ios-sim launch "$1" --devicetypeid "$2" --args "$3" --verbose &
 	
 	slim_system_wait
 }
@@ -62,21 +57,21 @@ ios_sim_launch() {
 run_test_system() {
 
 	local DEVICE_TYPE_IDENTIFIER=$(get_app_devicetypeid)
-	echo >&2 "[OCSP_RUN] Info: $(date)"
-	echo >&2 "[OCSP_RUN] Info: Test System SDK Deployment Target: $DEPLOYMENT_TARGET_VALUE"
-	echo >&2 "[OCSP_RUN] Info: Test System Executable Folder Path: $APPLICATION_PATH"
-	echo >&2 "[OCSP_RUN] Info: Simulator Device Identifier: $DEVICE_TYPE_IDENTIFIER"
+
+	echo "[OCSP_RUN] Info: Test System SDK Deployment Target: $DEPLOYMENT_TARGET_VALUE"
+	echo "[OCSP_RUN] Info: Test System Executable Folder Path: $APPLICATION_PATH"
+	echo "[OCSP_RUN] Info: Simulator Device Identifier: $DEVICE_TYPE_IDENTIFIER"
 
 	ios_sim_launch "$APPLICATION_PATH" "$DEVICE_TYPE_IDENTIFIER" "$SLIM_PORT"
 	return $?
 }
 
 check_node_exists() {
-	type npm >/dev/null 2>&1 || { echo >&2 "[OCSP_RUN] ERROR: Dependancy Check Failed: iOS based Acceptance Testing requires 'Node' and ios-sim (http://github.com/phonegap/ios-sim)"; echo >&2 "[OCSP_INFO] ERROR: For details of how to install Node visit http://blog.teamtreehouse.com/install-node-js-npm-mac"; exit 1; }
+	type npm >/dev/null 2>&1 || { echo >&2 "[OCSP_RUN] ERROR: Dependancy Check Failed: iOS based Acceptance Testing requires 'Node' and ios-sim (http://github.com/phonegap/ios-sim)\n[OCSP_INFO] ERROR: For details of how to install Node visit http://blog.teamtreehouse.com/install-node-js-npm-mac"; exit 1; }
 }
 
 preflight_iossim() {
-	type ios-sim >/dev/null 2>&1 || { echo >&2 "[OCSP_RUN] ERROR: Dependancy Check Failed: iOS based Acceptance Testing requires ios-sim (http://github.com/phonegap/ios-sim)"; echo >&2 "[OCSP_INFO] ERROR: Install using the Node Package Manager\n[OCSP_INFO] ERROR: Use '$ npm install ios-sim -g'"; exit 1; }
+	type ios-sim >/dev/null 2>&1 || { echo >&2 "[OCSP_RUN] ERROR: Dependancy Check Failed: iOS based Acceptance Testing requires ios-sim (http://github.com/phonegap/ios-sim)\n[OCSP_INFO] ERROR: Install using the Node Package Manager\n[OCSP_INFO] ERROR: Use '$ npm install ios-sim -g'"; exit 1; }
 	npm update ios-sim
 }	
 
@@ -87,7 +82,7 @@ check_test_system() {
 	
 }
 main() {
-	echo >&2 "[OCSP_RUN] == RunSlimTestTargetWithSlimPort~iOS:$SLIM_PORT =="
+	echo "[OCSP_RUN] == RunSlimTestTargetWithSlimPort~iOS:$SLIM_PORT =="
 	check_test_system
 	run_test_system
 	exit $?
