Add logging to example app.Export log form iOS systems to easily discoverable place

diff --git a/Pod/Support/iOS/RunTestsTargetWithSlimPort b/Pod/Support/iOS/RunTestsTargetWithSlimPort
--- a/Pod/Support/iOS/RunTestsTargetWithSlimPort
+++ b/Pod/Support/iOS/RunTestsTargetWithSlimPort
@@ -39,30 +39,57 @@ slim_system_wait() {
 }
 
 run_test_system() {
+
+	local START_TIME=$(date '+%Y-%m-%d %H:%M:%S')
+	start_slim
+
+ 	if [ $? == 0 ]; then 
+	 	slim_system_wait
+		print_test_system_log $START_TIME
+	else 
+		log_simctl_error
+	fi
+}
+
+start_slim() {
 	log "Start Slim Test Sytem"
 	$MYPATH/simctl $APPLICATION_PATH $SLIM_PORT
- 	if [ $? == 0 ]; then 
-	 	slim_system_wait; 
-	else 
-		log "**ABORTING** For details click the red/green 'Execution Log' button in Fitnesse to view stdout and stderr logs"
-	 	error "**ABORTING** Exit Code error detected when executing Slim Test Sytem with ($MYPATH/simctl)"
+}
+
+print_test_system_log() {
+	local LOGFILE=$($MYPATH/simctl log $1)
+	if [ -z $LOGFILE ]; then
+		log "*WARNING* No test system log messages were found (use os_log() or NSLog())"
+	else
+		print_logfile_contents $LOGFILE
 	fi
+}
+
+log_simctl_error() {
+	log "**ABORTING** Slim Test System reported an error. Check the executiong log for more details"
+	error "**ABORTING** Exit Code error detected when executing Slim Test Sytem with ($MYPATH/simctl)"
+}
+
+print_logfile_contents() {
+	log "********* $1 *********"
+	cat $1
+	log "********* End of Log ***********"
 }
 
 main() {
 	log "== RunSlimTestTargetWithSlimPort~iOS:$SLIM_PORT $(date)=="
-	log "Info: Test System Suggested SDK: $DEPLOYMENT_TARGET_VALUE"
-	log "Info: Test System Path: $APPLICATION_PATH"
+	log "Test System Suggested SDK: $DEPLOYMENT_TARGET_VALUE"
+	log "Test System Path: $APPLICATION_PATH"
 	run_test_system 
 	exit $?
 }
 
 log() {
-	echo "[OCSP_RUN] $1"
+	echo "[OCSP_RUN]: INFO $1"
 }
 
 error() {
-	>&2 echo "[OCSP_RUN] $1"
+	>&2 echo "[OCSP_RUN]: ERROR $1"
 	exit 1
 }
 
diff --git a/Pod/Support/iOS/simctl b/Pod/Support/iOS/simctl
--- a/Pod/Support/iOS/simctl
+++ b/Pod/Support/iOS/simctl
@@ -2,6 +2,9 @@
 
 APPLICATION_PATH=$1
 SLIMSERVER_PORT=$2
+PID_FILE=.simctl.pid
+ACTION=MAIN
+LOG_START_DATE=
 
 ## HELP ROUTINE
 
@@ -12,13 +15,15 @@ while [ "$1" != "" ]; do
 		-h | --help )			echo "Utility to 'xcrun simctl' for installing and launching iOS based acceptance test apps\n\nUsage: simctl <path-to-application-bundle> <slim-server-port-arg>"
 								exit 0
                                 ;;
+
+		log )					shift
+								ACTION=LOG
+								LOG_START_DATE="$1"
+								;;
 		esac
 		shift
 done
 
-
-## MAIN ROUTINE
-APP_IDENTIFIER=$(defaults read $APPLICATION_PATH/Info CFBundleIdentifier)
 
 check_device_booted() {
 	xcrun simctl list devices | grep -i booted
@@ -36,11 +41,11 @@ get_device_id() {
 }
 
 log() {
-	echo "[OCSP_SIMCTL] $1"
+	echo "[OCSP_SIMCTL] INFO: $1"
 }
 
 error() {
-	>&2 echo "[OCSP_SIMCTL] $1"
+	>&2 echo "[OCSP_SIMCTL] ERROR: $1"
 }
 
 preflight() {
@@ -57,23 +62,63 @@ install() {
 
 launch() {
 	log "Launching... (App Identifer:$APP_IDENTIFIER, Slim Port: $SLIMSERVER_PORT)"
-	local PID_FILE=.simctl.pid
 	rm $PID_FILE 2> /dev/null
 	echo $(xcrun simctl launch booted $APP_IDENTIFIER $SLIMSERVER_PORT) | cut -d " " -f2 > $PID_FILE
 }
 
+pid() {
+	cat $PID_FILE
+}
+
+write_logs() {
+
+	# DO NOT ECHO FROM HERE. OUTPUT IS RESERVERD FOR RETURNING THE FILENAME
+	
+	PID_ID=$(cat $PID_FILE)
+	local LOGDIR="Logs"
+	local LOGPATH="$(pwd)/$LOGDIR"
+	local LOGFILENAME="$(date +%Y%m%d-%H%M%S).log"
+	local LOGFILE="$LOGPATH/$LOGFILENAME"
+
+	mkdir -p $LOGPATH
+	xcrun simctl spawn booted log show --start $LOG_START_DATE --style compact --info --predicate "processID == $PID_ID" > $LOGFILE
+
+	# Check number of lines in logfile before returning a log file
+	if [ $(grep -c '' $LOGFILE) -eq 1 ]; then
+		rm $LOGFILE
+	else
+		echo $LOGFILE
+	fi
+	
+}
+
 main() {
+
 	log "== Launching Slim Host App $(xcrun simctl --version)  =="
+	APP_IDENTIFIER=$(defaults read $APPLICATION_PATH/Info CFBundleIdentifier)
+
 	preflight
+	
 	if install; then
 		launch
 	else
-		error "** ABORTING ** Error encountered launching app. (Check usage with --help)"
+		error '** ABORTING ** Error encountered launching app. (Check usage with --help)'
 	fi
+
 	exit $?
 }
 
-main
+case $ACTION in
+	'LOG')	
+			write_logs
+			;;
+	*)
+			
+			main
+			;;
+
+esac
+
 
 
 
